// <auto-generated />
using System;
using InvoiceMe.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InvoiceMe.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250806103336_Seed_Default_Users")]
    partial class Seed_Default_Users
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InvoiceMe.Server.Data.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UserId = new Guid("f6a84f3d-413c-49d8-8fb8-9319cdfde5a6")
                        },
                        new
                        {
                            Id = 2,
                            UserId = new Guid("af5fe090-404f-4b9e-a8da-dfd3a34cb2c1")
                        },
                        new
                        {
                            Id = 3,
                            UserId = new Guid("0ed76a7c-ca3c-45cf-a212-d54163a57f24")
                        });
                });

            modelBuilder.Entity("InvoiceMe.Server.Data.Models.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Tax")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("InvoiceMe.Server.Data.Models.InvoiceItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("InvoiceItems");
                });

            modelBuilder.Entity("InvoiceMe.Server.Data.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("ApprovalDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApprovedByName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BankType")
                        .HasColumnType("int");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<string>("ProofOfPayments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RejectReason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("InvoiceMe.Server.Data.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RefreshTokenCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RefreshTokenExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("VerificationToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a55f0dd2-a592-4e53-8179-ef1a3e26a71d"),
                            Address = "",
                            Avatar = "",
                            Email = "admin@gmail.com",
                            FirstName = "System",
                            IsActive = true,
                            LastName = "Admin",
                            PasswordHash = new byte[] { 187, 54, 247, 36, 57, 44, 88, 251, 98, 201, 155, 225, 113, 179, 196, 36, 197, 137, 226, 46, 76, 118, 77, 169, 14, 156, 80, 239, 169, 71, 147, 137, 198, 105, 252, 217, 56, 18, 96, 187, 104, 239, 154, 252, 25, 215, 220, 5, 6, 193, 15, 216, 158, 56, 61, 220, 225, 243, 169, 21, 142, 64, 74, 167 },
                            PasswordSalt = new byte[] { 64, 102, 107, 34, 239, 46, 128, 60, 29, 65, 171, 80, 154, 94, 49, 41, 206, 176, 41, 4, 114, 60, 13, 22, 223, 248, 133, 76, 198, 173, 46, 200, 197, 166, 7, 245, 80, 186, 8, 0, 68, 185, 237, 218, 69, 55, 29, 227, 129, 173, 205, 38, 153, 163, 23, 140, 142, 65, 3, 162, 195, 94, 235, 245, 25, 41, 109, 112, 119, 100, 248, 158, 53, 174, 200, 18, 95, 230, 138, 42, 17, 92, 132, 160, 202, 107, 125, 79, 38, 111, 111, 89, 240, 111, 16, 219, 247, 171, 175, 229, 114, 221, 77, 117, 135, 20, 141, 56, 56, 66, 254, 158, 246, 222, 36, 223, 137, 207, 13, 42, 96, 4, 46, 203, 64, 92, 178, 6 },
                            Phone = "",
                            RefreshToken = "",
                            RefreshTokenCreatedAt = new DateTime(2025, 8, 6, 18, 33, 36, 529, DateTimeKind.Unspecified).AddTicks(8575),
                            RefreshTokenExpiresAt = new DateTime(2025, 8, 13, 18, 33, 36, 529, DateTimeKind.Unspecified).AddTicks(8604),
                            Role = 0,
                            VerificationToken = ""
                        },
                        new
                        {
                            Id = new Guid("f6a84f3d-413c-49d8-8fb8-9319cdfde5a6"),
                            Address = "",
                            Avatar = "",
                            Email = "anna@gmail.com",
                            FirstName = "Anna",
                            IsActive = true,
                            LastName = "Cruz",
                            PasswordHash = new byte[] { 226, 156, 196, 169, 159, 88, 210, 7, 129, 146, 149, 241, 106, 209, 140, 137, 181, 171, 80, 5, 146, 59, 167, 211, 18, 202, 104, 108, 82, 116, 208, 66, 144, 151, 81, 89, 127, 187, 31, 17, 151, 85, 148, 56, 84, 242, 122, 47, 224, 195, 206, 179, 203, 223, 118, 220, 221, 161, 97, 159, 36, 17, 78, 242 },
                            PasswordSalt = new byte[] { 62, 137, 209, 209, 106, 210, 196, 26, 149, 136, 111, 22, 182, 23, 56, 255, 212, 220, 179, 188, 122, 28, 151, 158, 125, 53, 54, 27, 32, 83, 170, 139, 8, 131, 244, 67, 93, 62, 95, 73, 198, 138, 214, 111, 190, 41, 25, 48, 3, 36, 229, 225, 58, 178, 141, 91, 22, 95, 24, 91, 143, 238, 176, 203, 126, 199, 199, 21, 208, 240, 239, 89, 246, 78, 213, 172, 130, 0, 219, 185, 121, 211, 45, 85, 225, 129, 208, 243, 224, 184, 148, 50, 116, 87, 249, 51, 15, 38, 251, 10, 192, 23, 185, 70, 185, 7, 9, 25, 118, 181, 39, 52, 145, 208, 17, 89, 59, 176, 237, 68, 163, 83, 221, 192, 29, 77, 137, 49 },
                            Phone = "",
                            RefreshToken = "",
                            RefreshTokenCreatedAt = new DateTime(2025, 8, 6, 18, 33, 36, 529, DateTimeKind.Unspecified).AddTicks(8607),
                            RefreshTokenExpiresAt = new DateTime(2025, 8, 13, 18, 33, 36, 529, DateTimeKind.Unspecified).AddTicks(8608),
                            Role = 1,
                            VerificationToken = ""
                        },
                        new
                        {
                            Id = new Guid("af5fe090-404f-4b9e-a8da-dfd3a34cb2c1"),
                            Address = "",
                            Avatar = "",
                            Email = "mark@gmail.com",
                            FirstName = "Mark",
                            IsActive = true,
                            LastName = "Rivera",
                            PasswordHash = new byte[] { 124, 244, 138, 53, 64, 33, 87, 118, 172, 240, 70, 109, 207, 70, 235, 43, 121, 250, 241, 119, 32, 66, 40, 226, 43, 226, 94, 69, 160, 207, 26, 120, 93, 114, 69, 87, 193, 31, 32, 91, 92, 173, 142, 208, 208, 99, 155, 133, 229, 249, 172, 141, 67, 72, 21, 102, 164, 189, 22, 174, 75, 230, 34, 180 },
                            PasswordSalt = new byte[] { 232, 124, 255, 172, 192, 58, 79, 60, 14, 209, 235, 235, 19, 161, 165, 164, 148, 38, 65, 244, 144, 85, 45, 38, 173, 185, 100, 30, 29, 192, 232, 106, 241, 128, 129, 141, 219, 119, 51, 4, 55, 159, 190, 227, 68, 160, 114, 248, 35, 80, 145, 39, 83, 44, 148, 181, 142, 181, 117, 61, 175, 209, 78, 54, 215, 17, 32, 60, 33, 163, 118, 86, 37, 192, 244, 65, 235, 244, 206, 13, 51, 117, 117, 138, 104, 153, 222, 117, 48, 151, 127, 45, 244, 155, 50, 65, 194, 152, 136, 78, 91, 46, 37, 67, 243, 83, 170, 221, 200, 194, 121, 172, 84, 89, 128, 115, 200, 248, 27, 85, 82, 198, 193, 218, 59, 169, 207, 78 },
                            Phone = "",
                            RefreshToken = "",
                            RefreshTokenCreatedAt = new DateTime(2025, 8, 6, 18, 33, 36, 529, DateTimeKind.Unspecified).AddTicks(8609),
                            RefreshTokenExpiresAt = new DateTime(2025, 8, 13, 18, 33, 36, 529, DateTimeKind.Unspecified).AddTicks(8610),
                            Role = 1,
                            VerificationToken = ""
                        },
                        new
                        {
                            Id = new Guid("0ed76a7c-ca3c-45cf-a212-d54163a57f24"),
                            Address = "",
                            Avatar = "",
                            Email = "sofie@gmail.com",
                            FirstName = "Sofia",
                            IsActive = true,
                            LastName = "Lopez",
                            PasswordHash = new byte[] { 165, 242, 91, 37, 15, 149, 116, 181, 17, 217, 180, 111, 227, 65, 11, 47, 177, 51, 119, 208, 92, 139, 122, 146, 31, 213, 156, 223, 192, 204, 239, 94, 87, 134, 100, 203, 38, 118, 140, 237, 151, 91, 29, 72, 189, 184, 100, 164, 106, 163, 86, 98, 20, 2, 62, 182, 53, 188, 33, 64, 230, 164, 3, 202 },
                            PasswordSalt = new byte[] { 141, 135, 255, 150, 182, 110, 128, 48, 205, 34, 20, 44, 61, 98, 52, 174, 235, 25, 9, 254, 142, 155, 182, 80, 131, 180, 45, 206, 62, 72, 144, 34, 252, 103, 72, 14, 205, 25, 1, 27, 253, 237, 33, 149, 145, 88, 19, 223, 235, 171, 69, 96, 148, 234, 33, 198, 94, 116, 208, 166, 67, 178, 252, 88, 62, 251, 216, 99, 112, 146, 187, 131, 1, 90, 136, 155, 192, 155, 20, 81, 41, 22, 156, 247, 225, 54, 160, 237, 111, 4, 146, 55, 148, 180, 206, 180, 88, 117, 137, 191, 238, 238, 178, 233, 242, 180, 152, 214, 194, 66, 40, 109, 125, 37, 27, 0, 77, 177, 8, 127, 17, 95, 110, 20, 213, 109, 244, 243 },
                            Phone = "",
                            RefreshToken = "",
                            RefreshTokenCreatedAt = new DateTime(2025, 8, 6, 18, 33, 36, 529, DateTimeKind.Unspecified).AddTicks(8611),
                            RefreshTokenExpiresAt = new DateTime(2025, 8, 13, 18, 33, 36, 529, DateTimeKind.Unspecified).AddTicks(8612),
                            Role = 1,
                            VerificationToken = ""
                        });
                });

            modelBuilder.Entity("InvoiceMe.Server.Data.Models.Client", b =>
                {
                    b.HasOne("InvoiceMe.Server.Data.Models.User", "User")
                        .WithOne("Client")
                        .HasForeignKey("InvoiceMe.Server.Data.Models.Client", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("InvoiceMe.Server.Data.Models.Invoice", b =>
                {
                    b.HasOne("InvoiceMe.Server.Data.Models.Client", "Client")
                        .WithMany("Invoices")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("InvoiceMe.Server.Data.Models.InvoiceItem", b =>
                {
                    b.HasOne("InvoiceMe.Server.Data.Models.Invoice", "Invoice")
                        .WithMany("InvoiceItems")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("InvoiceMe.Server.Data.Models.Payment", b =>
                {
                    b.HasOne("InvoiceMe.Server.Data.Models.Invoice", "Invoice")
                        .WithMany("Payments")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("InvoiceMe.Server.Data.Models.Client", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("InvoiceMe.Server.Data.Models.Invoice", b =>
                {
                    b.Navigation("InvoiceItems");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("InvoiceMe.Server.Data.Models.User", b =>
                {
                    b.Navigation("Client");
                });
#pragma warning restore 612, 618
        }
    }
}
